### ISSUE TITLE
Dynamically assign the linear layer's neural numbers after CNN layers

### ISSUE THREAD

**Issue by GBLin5566** [GBLin5566/toward-controlled-generation-of-text-pytorch#2]
In https://github.com/GBLin5566/toward-controlled-generation-of-text-pytorch/blob/master/Model/Modules.py#L175, the number of neurons is fixed at 141952. 
It's would be nice to dynamically assign the neurons number according to CNN's kernel size.

**Comment by Syrup274** [comment]
Thanks for your code. Have you finish a runnable demo with a tolerable result yet?

**Comment by Syrup274** [comment]
Or will you consider implementing a Tensorflow version later?

**Comment by GBLin5566** [comment]
Hi @Syrup274 , thanks for the interests !
I'm still working on the code, so it is messy and not runnable for now.
It should be runnable in about two weeks (I guess...).
Also I won't do a tf version 'cause I'm not that familiar with tensorflow.
If you want to work on it, we could share some details about implementing the model. :)
