### ISSUE TITLE
Is it possible to generate sentences using the repo ?

### ISSUE THREAD

**Issue by jonzarecki** [GBLin5566/toward-controlled-generation-of-text-pytorch#6]
Hello, 
I've tried training the models using the code provided but I haven't found any code for generating new sentences. I've been wondering if anyone actually got to the part of generating sentences with the models trained, latent variables and all.
I know that `Generator` need to be used for that, but I'm confused about how it is trained and which function do I need to use in train.py, `main_alg` or `train_vae_with_attr_loss`.

I will be grateful for some help, thanks !

**Comment by GBLin5566** [comment]
Hi @yonilx , there might be a file called generate.py when the work is complete. (And LOTS of refactor of the code structure)
The problem I got stuck right now is #7 , and any advice would be helpful :)
Thanks for the interests and sorry for the late reply.
